### ISSUE TITLE
I was building it on Mingw64 and getting error

### ISSUE THREAD

**Issue by abdulbadii** [yasuhirokimura/eb#1]
I was trying to build it on Mingw64, while configuring getting error
```
$ ./configure
configure: loading site script /mingw64/etc/config.site
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
..
..
checking for mode_t... yes
checking for ssize_t... yes
checking for in_port_t... no
configure: error: Failed to get size of sin_port in struct sockaddr_in
```
How to solve this? Thanks before.

**Comment by yasuhirokimura** [comment]
I'm not the author of this software. Original is ftp://ftp.sra.co.jp/pub/misc/eb/eb-4.4.3.tar.bz2 . I imported it to GitHub for personal use. So I can't answer your question. Sorry.
